#!/bin/bash
# bash is required because we need bash's printf to guarantee a cross-platform
# timestamp format.

set -e
set -x

# standardize timezone to reduce build differences
export TZ=UTC
# run the clock at 5% speed, ant requires a moving clock
TIMESTAMP=`printf '@%(%Y-%m-%d %H:%M:%S)T x0.05' \
    $(git log -n1 --format=format:%at)`

git reset --hard
git clean -fdx

./setup-ant
cd libnetcipher
faketime -f "$TIMESTAMP" ant release-all

if which gpg > /dev/null; then
    if [ -z "`gpg --list-secret-keys`" ]; then
        echo "No GPG secret keys found, not signing APK"
    else
        jarname=netcipher-$(git describe)
        rm -f ${jarname}*.asc
        for f in ${jarname}*.*; do
            gpg --armor --detach-sign $f
        done
    fi
else
    echo "gpg not found, not signing APK"
fi
